project_name: bibikoffi

builds:
  - binary: bibikoffi
    main: ./

    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}

    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^doc:'
      - '^chore:'
      - '^test:'
      - '^tests:'

archives:
  - id: bibikoffi
    name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE

docker_manifests:
  - name_template: 'traefik/bibikoffi:{{ .Tag }}'
    image_templates:
      - 'traefik/bibikoffi:{{ .Tag }}-amd64'
      - 'traefik/bibikoffi:{{ .Tag }}-arm64'
  - name_template: 'traefik/bibikoffi:latest'
    image_templates:
      - 'traefik/bibikoffi:{{ .Tag }}-amd64'
      - 'traefik/bibikoffi:{{ .Tag }}-arm64'
  - name_template: 'traefik/bibikoffi:v{{ .Major }}.{{ .Minor }}'
    image_templates:
      - 'traefik/bibikoffi:v{{ .Major }}.{{ .Minor }}-amd64'
      - 'traefik/bibikoffi:v{{ .Major }}.{{ .Minor }}-arm64'

dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    dockerfile: buildx.Dockerfile
    image_templates:
      - 'traefik/bibikoffi:latest-amd64'
      - 'traefik/bibikoffi:{{ .Tag }}-amd64'
      - 'traefik/bibikoffi:v{{ .Major }}.{{ .Minor }}-amd64'
    build_flag_templates:
      - '--pull'
      # https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys
      - '--label=org.opencontainers.image.title={{.ProjectName}}'
      - '--label=org.opencontainers.image.description=Myrmica Bibikoffi - Closes stale issues'
      - '--label=org.opencontainers.image.source={{.GitURL}}'
      - '--label=org.opencontainers.image.url={{.GitURL}}'
      - '--label=org.opencontainers.image.documentation={{.GitURL}}'
      - '--label=org.opencontainers.image.created={{.Date}}'
      - '--label=org.opencontainers.image.revision={{.FullCommit}}'
      - '--label=org.opencontainers.image.version={{.Version}}'
      - '--platform=linux/amd64'

  - use: buildx
    goos: linux
    goarch: arm64
    dockerfile: buildx.Dockerfile
    image_templates:
      - 'traefik/bibikoffi:latest-arm64'
      - 'traefik/bibikoffi:{{ .Tag }}-arm64'
      - 'traefik/bibikoffi:v{{ .Major }}.{{ .Minor }}-arm64'
    build_flag_templates:
      - '--pull'
      # https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys
      - '--label=org.opencontainers.image.title={{.ProjectName}}'
      - '--label=org.opencontainers.image.description=Myrmica Bibikoffi - Closes stale issues'
      - '--label=org.opencontainers.image.source={{.GitURL}}'
      - '--label=org.opencontainers.image.url={{.GitURL}}'
      - '--label=org.opencontainers.image.documentation={{.GitURL}}'
      - '--label=org.opencontainers.image.created={{.Date}}'
      - '--label=org.opencontainers.image.revision={{.FullCommit}}'
      - '--label=org.opencontainers.image.version={{.Version}}'
      - '--platform=linux/arm64'
